### ISSUE TITLE
Issue reading values in the console

### ISSUE THREAD

**Issue by houston-n** [bakercp/ofxCloudPlatform#3]
@bakercp I'm having an issue trying to pull/access the image description and score and print it into the console output under the void ofApp::update(); function. I have managed to access them within the visionDebug file but I'm unsure how to access them without drawing all of the visionDebug screen.
![Screenshot 2019-11-11 at 08 58 51](https://user-images.githubusercontent.com/53183430/68574418-b8fabb80-0461-11ea-8538-6e1d9aa085cd.png)

Any help would be greatly appreciated.

**Comment by bakercp** [comment]
Hi there -- I'm a bit confused about what the problem is here ... the only thing I can think of is typically you don't draw from the update() function because the background will often be updated just before draw, essentially erasing anything drawn during the `ofApp::update()` function.

**Comment by houston-n** [comment]
Hi @bakercp, thanks for the response. I'm not wanting to draw anything I just want to be able to read the values of the description(); or score(); but in the main ofApp::update(); loop (so that I can use the values for other things).  I'm not sure how to get these values without calling the full visionDebug class thought (I don't need to draw any of the bounding boxes or annotations I just need the values).

Hope this helped you understand my issue.

**Comment by bakercp** [comment]
The `annotations` variable is just a vector:

```cpp
std::vector<ofxGCP::AnnotateImageResponse> annotations;
``` 
That vector consists of lots of other vectors. So you just have to use for-loops or some other method to locate the annotations you are interested in.  For instance, if you request face annotations, you might look for a single likelihood of an emotion like:

```cpp
    for (auto& annotation: annotations)
    {
        for (auto faceAnnotation: annotation.faceAnnotations())
        {
            std::cout << "There is a " << (faceAnnotation.angerLikelihood().value() * 100) << "% likelihood of anger in the following region: " << ofToString(faceAnnotation.boundingPoly().getVertices()) << std::endl;
        }
   l }
```

Each of the annotation types can be explored in this way.  It may be easiest to dig into the various annotation types to see what values are exposed.

The debug drawing file (https://github.com/bakercp/ofxCloudPlatform/blob/master/libs/ofxCloudPlatform/src/VisionDebug.cpp#L192) is just a set of functions that somewhat automates this process for debugging onscreen.  

You can find specific documentation for the various annotations here:

https://github.com/bakercp/ofxCloudPlatform/blob/master/libs/ofxCloudPlatform/include/ofx/CloudPlatform/VisionAnnotations.h
